# Generated by Django 3.2.8 on 2022-08-24 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20220824_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet_client',
            name='tokens',
        ),
    ]
