# Generated by Django 3.2.8 on 2022-08-18 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_auto_20220818_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo',
            name='tags',
        ),
    ]
