# Generated by Django 3.2.8 on 2022-08-18 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_remove_modelo_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='model.modelo'),
        ),
    ]
