# Generated by Django 3.2.8 on 2022-08-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_tags_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='model',
        ),
        migrations.AddField(
            model_name='modelo',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='model.Tags'),
        ),
    ]
