# Generated by Django 3.2.8 on 2022-08-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='value_token',
            field=models.FloatField(default=0.1),
        ),
    ]
