# Generated by Django 3.2.8 on 2022-08-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_configuration_value_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='value_token_transaction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
